import { Component, OnInit } from '@angular/core';
import { ModalController } from '@ionic/angular';

@Component({
  selector: 'app-search-breed',
  templateUrl: './search-breed.component.html',
  styleUrls: ['./search-breed.component.scss'],
})
export class SearchBreedComponent  implements OnInit {
  breeds: string[] = [
    "Labrador Retriever",
    "Pastor Alemán",
    "Golden Retriever",
    "Bulldog Francés",
    "Bulldog Inglés",
    "Chihuahua",
    "Poodle",
    "Doberman",
    "Boxer",
    "Rottweiler",
    "Dálmata",
    "Maltés",
    "Yorkshire Terrier",
    "Shih Tzu",
    "Schnauzer",
    "Bichón Frisé",
    "Cocker Spaniel",
    "Border Collie",
    "Jack Russell Terrier",
    "Beagle",
    "Pomerania",
    "Husky Siberiano",
    "Akita Inu",
    "Mastín",
    "Shar Pei",
    "San Bernardo",
    "Terranova",
    "Dachshund (Teckel)",
    "Pug (Carlino)",
    "Bóxer",
    "Basset Hound",
    "Weimaraner",
    "Whippet",
    "West Highland White Terrier",
    "Bull Terrier",
    "Cane Corso",
    "Chow Chow",
    "Corgi",
    "Galgo",
    "Gran Danés",
    "Lebrel Afgano",
    "Malamute de Alaska",
    "Pekinés",
    "Pinscher",
    "Podenco",
    "Setter Irlandés",
    "Shar Pei",
    "Shiba Inu",
    "Spitz Japonés",
    "Terrier Escocés",
    "Terrier Galés",
    "Terrier Tibetano",
    "Teckel",
    "Toy Poodle",
    "Vizsla",
    "Welsh Corgi Pembroke",
    "Pastor Belga",
    "Boyero de Berna",
    "Samoyedo",
    "Schnauzer Gigante",
    "Setter Inglés",
    "Setter Gordon",
    "Akita Americano",
    "American Pitbull Terrier",
    "American Staffordshire Terrier",
    "Bóxer Americano",
    "Bulldog Americano",
    "Caniche Toy",
    "Cavalier King Charles Spaniel",
    "Collie",
    "Dogo Argentino",
    "Dogo de Burdeos",
    "English Springer Spaniel",
    "Eurasier",
    "Fox Terrier",
    "Grifón de Bruselas",
    "Husky Alaskan Malamute",
    "Maltipoo",
    "Mastín Napolitano",
    "Papillon",
    "Perro Crestado Chino",
    "Perro Lobo",
    "Presa Canario",
    "Puggle",
    "Sabueso",
    "Schipperke",
    "Schnoodle",
    "Schnauzer Miniatura",
    "Scottish Terrier",
    "Shepherd Inglés",
    "Sheltie",
    "Staffordshire Bull Terrier",
    "Teacup Poodle",
    "Teacup Yorkie",
    "Toy Fox Terrier",
    "Westiepoo",
    "Whoodle",
    "Cocker Spaniel Inglés",
    "Cairn Terrier",
    "Lhasa Apso",
    "Caniche enano",
    "Rat Terrier",
    "Cocker"
  ]
  filterBreed: string = ''
  constructor(
    private modalCtrl: ModalController
  ) { }

  ngOnInit() {}

  cancel() {
    return this.modalCtrl.dismiss(null);
  }
  selectBreed(breed: string) {
    return this.modalCtrl.dismiss(breed);
  }
}
